Rails.logger.info 'Starting ArmorShield seed'
Rails.logger.info 'Destroying all ArmorShields'
ArmorShield.destroy_all

Rails.logger.info 'Creating ArmorShields'
ArmorShield.insert_all!(
  [
    {
      name: 'Padded',
      base_ac: 11,
      ac_modifier: :dexterity,
      cap_ac_modifier: nil,
      strength: nil,
      stealth_disadvantage: true,
      weight: 8,
      cost_cp: 500,
      don_unit: :minute,
      don_amount: 1,
      doff_unit: :minute,
      doff_amount: 1,
      category: :light
    },
    {
      name: 'Leather',
      base_ac: 11,
      ac_modifier: :dexterity,
      cap_ac_modifier: nil,
      strength: nil,
      stealth_disadvantage: false,
      weight: 10,
      cost_cp: 1000,
      don_unit: :minute,
      don_amount: 1,
      doff_unit: :minute,
      doff_amount: 1,
      category: :light
    },
    {
      name: 'Studded Leather',
      base_ac: 12,
      ac_modifier: :dexterity,
      cap_ac_modifier: nil,
      strength: nil,
      stealth_disadvantage: false,
      weight: 13,
      cost_cp: 4500,
      don_unit: :minute,
      don_amount: 1,
      doff_unit: :minute,
      doff_amount: 1,
      category: :light
    },
    {
      name: 'Studded Leather',
      base_ac: 12,
      ac_modifier: :dexterity,
      cap_ac_modifier: nil,
      strength: nil,
      stealth_disadvantage: false,
      weight: 13,
      cost_cp: 4500,
      don_unit: :minute,
      don_amount: 1,
      doff_unit: :minute,
      doff_amount: 1,
      category: :medium
    },
    {
      name: 'Hide',
      base_ac: 12,
      ac_modifier: :dexterity,
      cap_ac_modifier: 2,
      strength: nil,
      stealth_disadvantage: false,
      weight: 12,
      cost_cp: 1000,
      don_unit: :minute,
      don_amount: 5,
      doff_unit: :minute,
      doff_amount: 1,
      category: :medium
    },
    {
      name: 'Chain Shirt',
      base_ac: 13,
      ac_modifier: :dexterity,
      cap_ac_modifier: 2,
      strength: nil,
      stealth_disadvantage: false,
      weight: 20,
      cost_cp: 5000,
      don_unit: :minute,
      don_amount: 5,
      doff_unit: :minute,
      doff_amount: 1,
      category: :medium
    },
    {
      name: 'Scale Mail',
      base_ac: 14,
      ac_modifier: :dexterity,
      cap_ac_modifier: 2,
      strength: nil,
      stealth_disadvantage: true,
      weight: 45,
      cost_cp: 5000,
      don_unit: :minute,
      don_amount: 10,
      doff_unit: :minute,
      doff_amount: 5,
      category: :medium
    },
    {
      name: 'Spiked Armor',
      base_ac: 14,
      ac_modifier: :dexterity,
      cap_ac_modifier: 2,
      strength: nil,
      stealth_disadvantage: true,
      weight: 45,
      cost_cp: 7500,
      don_unit: :minute,
      don_amount: 10,
      doff_unit: :minute,
      doff_amount: 5,
      category: :medium
    },
    {
      name: 'Breastplate',
      base_ac: 14,
      ac_modifier: :dexterity,
      cap_ac_modifier: 2,
      strength: nil,
      stealth_disadvantage: false,
      weight: 20,
      cost_cp: 40000,
      don_unit: :minute,
      don_amount: 5,
      doff_unit: :minute,
      doff_amount: 1,
      category: :medium
    },
    {
      name: 'Halfplate',
      base_ac: 15,
      ac_modifier: :dexterity,
      cap_ac_modifier: 2,
      strength: nil,
      stealth_disadvantage: true,
      weight: 40,
      cost_cp: 75000,
      don_unit: :minute,
      don_amount: 5,
      doff_unit: :minute,
      doff_amount: 1,
      category: :medium
    },
    {
      name: 'Ring Mail',
      base_ac: 14,
      ac_modifier: nil,
      cap_ac_modifier: nil,
      strength: nil,
      stealth_disadvantage: true,
      weight: 40,
      cost_cp: 3000,
      don_unit: :minute,
      don_amount: 10,
      doff_unit: :minute,
      doff_amount: 5,
      category: :heavy
    },
    {
      name: 'Chain Mail',
      base_ac: 16,
      ac_modifier: nil,
      cap_ac_modifier: nil,
      strength: 13,
      stealth_disadvantage: true,
      weight: 55,
      cost_cp: 7500,
      don_unit: :minute,
      don_amount: 10,
      doff_unit: :minute,
      doff_amount: 5,
      category: :heavy
    },
    {
      name: 'Splint',
      base_ac: 17,
      ac_modifier: nil,
      cap_ac_modifier: nil,
      strength: 15,
      stealth_disadvantage: true,
      weight: 60,
      cost_cp: 20000,
      don_unit: :minute,
      don_amount: 10,
      doff_unit: :minute,
      doff_amount: 5,
      category: :heavy
    },
    {
      name: 'Plate',
      base_ac: 18,
      ac_modifier: nil,
      cap_ac_modifier: nil,
      strength: 15,
      stealth_disadvantage: true,
      weight: 65,
      cost_cp: 15000,
      don_unit: :minute,
      don_amount: 10,
      doff_unit: :minute,
      doff_amount: 5,
      category: :heavy
    },
    {
      name: 'Shield',
      base_ac: 2,
      ac_modifier: nil,
      cap_ac_modifier: nil,
      strength: nil,
      stealth_disadvantage: true,
      weight: 6,
      cost_cp: 1000,
      don_unit: :action,
      don_amount: 1,
      doff_unit: :action,
      doff_amount: 1,
      category: :shield
    }
  ]
)

Rails.logger.info 'Finished ArmorShield seed'