require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/01_armor_shields.rb", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ArmorShield. As you add validations to ArmorShield, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ArmorShield.create! valid_attributes
      get armor_shields_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      armor_shield = ArmorShield.create! valid_attributes
      get armor_shield_url(armor_shield)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_armor_shield_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      armor_shield = ArmorShield.create! valid_attributes
      get edit_armor_shield_url(armor_shield)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ArmorShield" do
        expect {
          post armor_shields_url, params: { armor_shield: valid_attributes }
        }.to change(ArmorShield, :count).by(1)
      end

      it "redirects to the created armor_shield" do
        post armor_shields_url, params: { armor_shield: valid_attributes }
        expect(response).to redirect_to(armor_shield_url(ArmorShield.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ArmorShield" do
        expect {
          post armor_shields_url, params: { armor_shield: invalid_attributes }
        }.to change(ArmorShield, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post armor_shields_url, params: { armor_shield: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested armor_shield" do
        armor_shield = ArmorShield.create! valid_attributes
        patch armor_shield_url(armor_shield), params: { armor_shield: new_attributes }
        armor_shield.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the armor_shield" do
        armor_shield = ArmorShield.create! valid_attributes
        patch armor_shield_url(armor_shield), params: { armor_shield: new_attributes }
        armor_shield.reload
        expect(response).to redirect_to(armor_shield_url(armor_shield))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        armor_shield = ArmorShield.create! valid_attributes
        patch armor_shield_url(armor_shield), params: { armor_shield: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested armor_shield" do
      armor_shield = ArmorShield.create! valid_attributes
      expect {
        delete armor_shield_url(armor_shield)
      }.to change(ArmorShield, :count).by(-1)
    end

    it "redirects to the 01_armor_shields.rb list" do
      armor_shield = ArmorShield.create! valid_attributes
      delete armor_shield_url(armor_shield)
      expect(response).to redirect_to(armor_shields_url)
    end
  end
end
