default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV.fetch('POSTGRES_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'postgres' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'postgres' } %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB_TEST') { 'postgres_test' } %>